# -*- coding: utf-8 -*-
"""actividad #1 POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_tMchvJ05WeouIDXv29HggWBgPtHQ9Z
"""

class Pago:
    @staticmethod
    def calcular_salario_bruto(horas_trabajadas, valor_hora):
        return horas_trabajadas * valor_hora

    @staticmethod
    def calcular_valor_retefuente(porcentaje_retefuente, salario_bruto):
        return porcentaje_retefuente * salario_bruto

    @staticmethod
    def calcular_salario_neto(salario_bruto, valor_retefuente):
        return salario_bruto - valor_retefuente


horas_t =float(input("ingrese las horas trabajadas: "))
valor_hora = float(input("ingrese el valor de la hora: "))
retencion = float(input("ingrese el % de la retención en la fuente: "))

porcentaje_retefuente = retencion / 100

salario_bruto = Pago.calcular_salario_bruto(horas_t, valor_hora)
valor_retefuente = Pago.calcular_valor_retefuente(porcentaje_retefuente, salario_bruto)
salario_neto = Pago.calcular_salario_neto(salario_bruto, valor_retefuente)

print("Salario Bruto:", salario_bruto)
print("Retención en la Fuente:", valor_retefuente)
print("Salario Neto:", salario_neto)


#este si

import math
class Operaciones:
  @staticmethod
  def calcular_x(x,y):
    return x + math.pow (y,2)


x=float(input("Ingrese el valor de x "))
y=float(input("Ingrese el valor de y "))

suma=0
suma=suma + x
x=Operaciones.calcular_x(x,y)
suma=suma + (x/y)

print(f"el valor de x es: {x}")
print(f"el valor de y es: {y}")
print(f"el valor de la suma es: {suma}")

# este si

import math
class Calculos:
  @staticmethod
  def calcular_cuadrado(numero):
    return math.pow(numero,2)

  @staticmethod
  def calcular_cubo(numero):
    return math.pow(numero,3)

numero= float(input("Ingrese un numero: "))

cuadrado= Calculos.calcular_cuadrado(numero)
cubo= Calculos.calcular_cubo(numero)

print(f"cuadrado: {cuadrado}")
print(f"cubo: {cubo}")

#ESTE SI

import math
class calculos:
  @staticmethod
  def calcular_long_circunferencia(radio):
    return 2 * math.pi * radio
  @staticmethod
  def calcular_area_circulo(radio):
    return math.pi * math.pow(radio, 2)


radio = float(input("ingrese el radio de la circulo "))

longitud_circunferencia = calculos.calcular_long_circunferencia(radio)
area_circulo= calculos.calcular_area_circulo(radio)

print(f"longitud de la circunferencia: {longitud_circunferencia}")
print(f"area del circulo: {area_circulo}")

#ESTE SI

class Edades:
    @staticmethod
    def calcular_edalber(edjuan):
        return 2 * edjuan / 3

    @staticmethod
    def calcular_edana(edjuan):
        return 4 * edjuan / 3

    @staticmethod
    def calcular_edmama(edjuan, edalber, edana):
        return edjuan + edalber + edana


def main():
    print("Ingrese la edad de Juan")
    edjuan = float(input())

    edalber = Edades.calcular_edalber(edjuan)
    edana = Edades.calcular_edana(edjuan)
    edmama = Edades.calcular_edmama(edjuan, edalber, edana)

    print(f"Edad de Alberto: {edalber}")
    print(f"Edad de Ana: {edana}")
    print(f"Edad de Juan: {edjuan}")
    print(f"Edad de la Mama: {edmama}")


if __name__ == "__main__":
    main()